In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 讀入大專校院圖書館統計

In [2]:
df=pd.read_csv("http://stats.moe.gov.tw/files/detail/107/107_library2.csv")

In [3]:
df.head()

,學校代碼,學校名稱,中文圖書收藏冊數(冊)-總類,中文圖書收藏冊數(冊)-哲學類,中文圖書收藏冊數(冊)-宗教類,中文圖書收藏冊數(冊)-科學類,中文圖書收藏冊數(冊)-應用科學類,中文圖書收藏冊數(冊)-社會科學類,中文圖書收藏冊數(冊)-史地類,中文圖書收藏冊數(冊)-語言文學類,...,電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),報紙(種),中.日文期刊(種),西文期刊(種)
0,1,國立政治大學,326716,50264,37698,31415,75396,301584,213622,201056,...,60524,741894,24603,2978,128733,386198,2732587,87,1826,1403
1,2,國立清華大學,80330,45612,25154,70903,87839,216160,129770,199748,...,150970,3546844,122765,3440,168306,461470,239163,27,2133,785
2,3,國立臺灣大學,144181,71021,43498,114475,325568,429073,281869,291545,...,54046,3206992,184316,3938,155454,481978,32772687,27,1990,1193
3,4,國立臺灣師範大學,142017,74321,24630,62745,77572,256911,161588,218935,...,107991,2649583,75182,1182,72631,194715,7685907,14,969,1492
4,5,國立成功大學,191300,35686,22415,43386,108872,126172,103013,128309,...,75040,784869,58257,2663,78764,493694,5359587,16,1809,171

# 算出館藏資源

In [4]:
df["館藏資源"] = df.loc[:,"中文圖書收藏冊數(冊)-總類":"視聽資料(件)"].sum(axis=1)

In [5]:
df.head()

,學校代碼,學校名稱,中文圖書收藏冊數(冊)-總類,中文圖書收藏冊數(冊)-哲學類,中文圖書收藏冊數(冊)-宗教類,中文圖書收藏冊數(冊)-科學類,中文圖書收藏冊數(冊)-應用科學類,中文圖書收藏冊數(冊)-社會科學類,中文圖書收藏冊數(冊)-史地類,中文圖書收藏冊數(冊)-語言文學類,...,電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),報紙(種),中.日文期刊(種),西文期刊(種),館藏資源
0,1,國立政治大學,326716,50264,37698,31415,75396,301584,213622,201056,...,741894,24603,2978,128733,386198,2732587,87,1826,1403,2932900
1,2,國立清華大學,80330,45612,25154,70903,87839,216160,129770,199748,...,3546844,122765,3440,168306,461470,239163,27,2133,785,5545284
2,3,國立臺灣大學,144181,71021,43498,114475,325568,429073,281869,291545,...,3206992,184316,3938,155454,481978,32772687,27,1990,1193,8525550
3,4,國立臺灣師範大學,142017,74321,24630,62745,77572,256911,161588,218935,...,2649583,75182,1182,72631,194715,7685907,14,969,1492,4579179
4,5,國立成功大學,191300,35686,22415,43386,108872,126172,103013,128309,...,784869,58257,2663,78764,493694,5359587,16,1809,171,2752565

# 以館藏資源為主、全年圖書借閱人次為輔找出前五高的學校

In [6]:
df.sort_values(by=["館藏資源","全年圖書(含視聽資料及其他館藏)借閱人次(人次)"], ascending=False).head()

,學校代碼,學校名稱,中文圖書收藏冊數(冊)-總類,中文圖書收藏冊數(冊)-哲學類,中文圖書收藏冊數(冊)-宗教類,中文圖書收藏冊數(冊)-科學類,中文圖書收藏冊數(冊)-應用科學類,中文圖書收藏冊數(冊)-社會科學類,中文圖書收藏冊數(冊)-史地類,中文圖書收藏冊數(冊)-語言文學類,...,電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),報紙(種),中.日文期刊(種),西文期刊(種),館藏資源
2,3,國立臺灣大學,144181,71021,43498,114475,325568,429073,281869,291545,...,3206992,184316,3938,155454,481978,32772687,27,1990,1193,8525550
52,1006,中國文化大學,128892,59325,23653,64052,100481,178156,137461,170861,...,5803536,58995,1827,68029,217457,1515700,13,473,273,7328881
1,2,國立清華大學,80330,45612,25154,70903,87839,216160,129770,199748,...,3546844,122765,3440,168306,461470,239163,27,2133,785,5545284
3,4,國立臺灣師範大學,142017,74321,24630,62745,77572,256911,161588,218935,...,2649583,75182,1182,72631,194715,7685907,14,969,1492,4579179
51,1005,淡江大學,87549,52391,16847,74774,118631,201952,111877,190870,...,2585059,69948,3185,137096,284450,611503,23,923,458,4144086

# 以全年圖書借閱人次為主、館藏資源為輔找出前五高的學校

In [7]:
df.sort_values(by=["全年圖書(含視聽資料及其他館藏)借閱人次(人次)","館藏資源"], ascending=False).head()

,學校代碼,學校名稱,中文圖書收藏冊數(冊)-總類,中文圖書收藏冊數(冊)-哲學類,中文圖書收藏冊數(冊)-宗教類,中文圖書收藏冊數(冊)-科學類,中文圖書收藏冊數(冊)-應用科學類,中文圖書收藏冊數(冊)-社會科學類,中文圖書收藏冊數(冊)-史地類,中文圖書收藏冊數(冊)-語言文學類,...,電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),報紙(種),中.日文期刊(種),西文期刊(種),館藏資源
1,2,國立清華大學,80330,45612,25154,70903,87839,216160,129770,199748,...,3546844,122765,3440,168306,461470,239163,27,2133,785,5545284
64,1018,朝陽科技大學,11050,26450,13098,42515,80570,92643,28049,83984,...,994968,50660,1290,164164,234206,1784664,20,635,114,1634985
2,3,國立臺灣大學,144181,71021,43498,114475,325568,429073,281869,291545,...,3206992,184316,3938,155454,481978,32772687,27,1990,1193,8525550
51,1005,淡江大學,87549,52391,16847,74774,118631,201952,111877,190870,...,2585059,69948,3185,137096,284450,611503,23,923,458,4144086
0,1,國立政治大學,326716,50264,37698,31415,75396,301584,213622,201056,...,741894,24603,2978,128733,386198,2732587,87,1826,1403,2932900

# 找出"書本"和"期刊"數位化最高的學校
## 首先用sum算出紙本"書"和"期刊"的數量

In [8]:
df["書(紙本)資源"] = df.loc[:,"中文圖書收藏冊數(冊)-總類":"外文圖書收藏冊數(冊)"].sum(axis=1)

In [9]:
df.head()

,學校代碼,學校名稱,中文圖書收藏冊數(冊)-總類,中文圖書收藏冊數(冊)-哲學類,中文圖書收藏冊數(冊)-宗教類,中文圖書收藏冊數(冊)-科學類,中文圖書收藏冊數(冊)-應用科學類,中文圖書收藏冊數(冊)-社會科學類,中文圖書收藏冊數(冊)-史地類,中文圖書收藏冊數(冊)-語言文學類,...,視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),報紙(種),中.日文期刊(種),西文期刊(種),館藏資源,書(紙本)資源
0,1,國立政治大學,326716,50264,37698,31415,75396,301584,213622,201056,...,24603,2978,128733,386198,2732587,87,1826,1403,2932900,1873299
1,2,國立清華大學,80330,45612,25154,70903,87839,216160,129770,199748,...,122765,3440,168306,461470,239163,27,2133,785,5545284,1350888
2,3,國立臺灣大學,144181,71021,43498,114475,325568,429073,281869,291545,...,184316,3938,155454,481978,32772687,27,1990,1193,8525550,4196045
3,4,國立臺灣師範大學,142017,74321,24630,62745,77572,256911,161588,218935,...,75182,1182,72631,194715,7685907,14,969,1492,4579179,1615092
4,5,國立成功大學,191300,35686,22415,43386,108872,126172,103013,128309,...,58257,2663,78764,493694,5359587,16,1809,171,2752565,1390816

In [10]:
df["期刊(紙本)資源"] = df.loc[:, ["期刊合訂本(未以圖書編目)(冊)", "報紙(種)","中.日文期刊(種)","西文期刊(種)"]].sum(axis=1)

In [11]:
df.head()

,學校代碼,學校名稱,中文圖書收藏冊數(冊)-總類,中文圖書收藏冊數(冊)-哲學類,中文圖書收藏冊數(冊)-宗教類,中文圖書收藏冊數(冊)-科學類,中文圖書收藏冊數(冊)-應用科學類,中文圖書收藏冊數(冊)-社會科學類,中文圖書收藏冊數(冊)-史地類,中文圖書收藏冊數(冊)-語言文學類,...,圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),報紙(種),中.日文期刊(種),西文期刊(種),館藏資源,書(紙本)資源,期刊(紙本)資源
0,1,國立政治大學,326716,50264,37698,31415,75396,301584,213622,201056,...,2978,128733,386198,2732587,87,1826,1403,2932900,1873299,235613
1,2,國立清華大學,80330,45612,25154,70903,87839,216160,129770,199748,...,3440,168306,461470,239163,27,2133,785,5545284,1350888,376313
2,3,國立臺灣大學,144181,71021,43498,114475,325568,429073,281869,291545,...,3938,155454,481978,32772687,27,1990,1193,8525550,4196045,886763
3,4,國立臺灣師範大學,142017,74321,24630,62745,77572,256911,161588,218935,...,1182,72631,194715,7685907,14,969,1492,4579179,1615092,133454
4,5,國立成功大學,191300,35686,22415,43386,108872,126172,103013,128309,...,2663,78764,493694,5359587,16,1809,171,2752565,1390816,444993

# 因為列的種類太多，把細分的書本跟期刊種類類別刪掉

In [12]:
df.drop(labels=["中文圖書收藏冊數(冊)-總類","中文圖書收藏冊數(冊)-哲學類","中文圖書收藏冊數(冊)-宗教類","中文圖書收藏冊數(冊)-科學類","中文圖書收藏冊數(冊)-應用科學類","中文圖書收藏冊數(冊)-社會科學類","中文圖書收藏冊數(冊)-史地類","中文圖書收藏冊數(冊)-語言文學類","中文圖書收藏冊數(冊)-藝術類","外文圖書收藏冊數(冊)","期刊合訂本(未以圖書編目)(冊)","報紙(種)","西文期刊(種)","中.日文期刊(種)"],axis=1,inplace = True)

In [13]:
df.head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源
0,1,國立政治大學,249,34,60524,741894,24603,2978,128733,386198,2732587,2932900,1873299,235613
1,2,國立清華大學,449,0,150970,3546844,122765,3440,168306,461470,239163,5545284,1350888,376313
2,3,國立臺灣大學,598,0,54046,3206992,184316,3938,155454,481978,32772687,8525550,4196045,886763
3,4,國立臺灣師範大學,352,0,107991,2649583,75182,1182,72631,194715,7685907,4579179,1615092,133454
4,5,國立成功大學,560,26,75040,784869,58257,2663,78764,493694,5359587,2752565,1390816,444993

# 算出"期刊數位化程度"和"書本數位化程度"

In [14]:
df['期刊數位化程度'] = df.apply(lambda x: x['電子期刊(種)'] / x['期刊(紙本)資源'], axis=1)

In [15]:
df.head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度
0,1,國立政治大學,249,34,60524,741894,24603,2978,128733,386198,2732587,2932900,1873299,235613,0.256879
1,2,國立清華大學,449,0,150970,3546844,122765,3440,168306,461470,239163,5545284,1350888,376313,0.401182
2,3,國立臺灣大學,598,0,54046,3206992,184316,3938,155454,481978,32772687,8525550,4196045,886763,0.060948
3,4,國立臺灣師範大學,352,0,107991,2649583,75182,1182,72631,194715,7685907,4579179,1615092,133454,0.809200
4,5,國立成功大學,560,26,75040,784869,58257,2663,78764,493694,5359587,2752565,1390816,444993,0.168632

In [16]:
df['書本數位化程度'] = df.apply(lambda x: x['電子書(種)'] / x['書(紙本)資源'], axis=1)

In [17]:
df.head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
0,1,國立政治大學,249,34,60524,741894,24603,2978,128733,386198,2732587,2932900,1873299,235613,0.256879,0.396036
1,2,國立清華大學,449,0,150970,3546844,122765,3440,168306,461470,239163,5545284,1350888,376313,0.401182,2.625565
2,3,國立臺灣大學,598,0,54046,3206992,184316,3938,155454,481978,32772687,8525550,4196045,886763,0.060948,0.764289
3,4,國立臺灣師範大學,352,0,107991,2649583,75182,1182,72631,194715,7685907,4579179,1615092,133454,0.809200,1.640515
4,5,國立成功大學,560,26,75040,784869,58257,2663,78764,493694,5359587,2752565,1390816,444993,0.168632,0.564323

# 依據"書本數位化程度"與"期刊數位化程度"排出前五名的學校

In [18]:
df.sort_values(by="書本數位化程度", ascending=False).head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
29,35,國立臺南藝術大學,121,2,32876,1982149,32088,273,14986,61435,41315,2277376,207022,23579,1.394292,9.574581
70,1024,崑山科技大學,215,3,23041,3193530,19744,2000,17818,65425,178515,3617515,349260,32823,0.701977,9.143704
75,1029,中山醫學大學,120,6,23784,1169544,18377,515,27861,66512,1242333,1503466,208902,83001,0.286551,5.598529
66,1020,南華大學,195,10,15554,1793691,25085,534,22158,70028,93311,2241481,382637,24945,0.623532,4.687709
52,1006,中國文化大學,253,0,67259,5803536,58995,1827,68029,217457,1515700,7328881,1398838,759,88.615283,4.148826

In [19]:
df.sort_values(by="期刊數位化程度", ascending=False).head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
117,1072,大華科技大學,140,43,37519,392771,17065,1015,1987,13756,11375,688770,241232,80,468.987500,1.628188
55,1009,長庚大學,204,4,115764,272840,30539,1348,36556,117765,2073879,820823,401472,354,327.016949,0.679599
65,1019,高雄醫學大學,129,2,27902,84495,14024,1163,26559,65211,304537,292032,165480,127,219.700787,0.510606
36,46,國立臺北護理健康大學,92,0,45539,106559,41902,340,32049,86029,610622,474971,280879,239,190.539749,0.379377
144,1284,樹人醫護管理專科學校,36,0,70311,25035,6108,326,10985,30175,204823,259918,158428,389,180.748072,0.158021

In [20]:
df.sort_values(by=["書本數位化程度","期刊數位化程度"], ascending=False).head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
29,35,國立臺南藝術大學,121,2,32876,1982149,32088,273,14986,61435,41315,2277376,207022,23579,1.394292,9.574581
70,1024,崑山科技大學,215,3,23041,3193530,19744,2000,17818,65425,178515,3617515,349260,32823,0.701977,9.143704
75,1029,中山醫學大學,120,6,23784,1169544,18377,515,27861,66512,1242333,1503466,208902,83001,0.286551,5.598529
66,1020,南華大學,195,10,15554,1793691,25085,534,22158,70028,93311,2241481,382637,24945,0.623532,4.687709
52,1006,中國文化大學,253,0,67259,5803536,58995,1827,68029,217457,1515700,7328881,1398838,759,88.615283,4.148826

In [21]:
df_sort=df.sort_values("期刊數位化程度",ascending=False)

In [22]:
df_sort.index=range(1,154)

# 看政大的排名

In [23]:
df_sort[df_sort.學校名稱=="國立政治大學"]

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
133,1,國立政治大學,249,34,60524,741894,24603,2978,128733,386198,2732587,2932900,1873299,235613,0.256879,0.396036

In [24]:
df_sort=df.sort_values("書本數位化程度",ascending=False)

In [25]:
df_sort.index = range(1,154)

In [26]:
df_sort[df_sort.學校名稱=="國立政治大學"]

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
104,1,國立政治大學,249,34,60524,741894,24603,2978,128733,386198,2732587,2932900,1873299,235613,0.256879,0.396036

In [27]:
df.describe()

,學校代碼,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
count,153.000000,153.000000,153.000000,153.000000,1.530000e+02,153.000000,153.000000,153.000000,153.000000,1.530000e+02,1.530000e+02,1.530000e+02,153.000000,153.000000,153.000000
mean,773.267974,147.856209,7.915033,37681.588235,5.044064e+05,22491.516340,872.816993,31220.346405,84096.339869,9.671631e+05,1.011696e+06,4.118256e+05,35956.895425,22.564544,1.077411
std,520.789115,123.424568,18.702289,28368.758188,8.078446e+05,24165.696292,678.368471,32433.761389,96522.802162,2.874667e+06,1.232841e+06,4.384544e+05,90969.536416,57.508245,1.362486
min,1.000000,7.000000,0.000000,0.000000,1.700000e+01,1164.000000,72.000000,337.000000,1096.000000,4.250000e+02,7.595700e+04,4.779600e+04,52.000000,0.000000,0.000026
25%,48.000000,60.000000,0.000000,17264.000000,7.224900e+04,8264.000000,463.000000,8376.000000,23423.000000,9.331100e+04,3.637970e+05,2.089020e+05,1006.000000,0.623532,0.306855
50%,1030.000000,119.000000,0.000000,32876.000000,1.865690e+05,14024.000000,683.000000,19890.000000,55351.000000,2.827910e+05,5.589900e+05,2.934350e+05,10590.000000,1.757436,0.657735
75%,1069.000000,206.000000,5.000000,55588.000000,5.934930e+05,26411.000000,1101.000000,43471.000000,112587.000000,8.616340e+05,1.158912e+06,4.107210e+05,32009.000000,11.906032,1.415307
max,3002.000000,765.000000,118.000000,150970.000000,5.803536e+06,184316.000000,3938.000000,168306.000000,542864.000000,3.277269e+07,8.525550e+06,4.196045e+06,886763.000000,468.987500,9.574581

In [28]:
df.sort_values(by="圖書閱覽座位數(個)", ascending=False).head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
2,3,國立臺灣大學,598,0,54046,3206992,184316,3938,155454,481978,32772687,8525550,4196045,886763,0.060948,0.764289
1,2,國立清華大學,449,0,150970,3546844,122765,3440,168306,461470,239163,5545284,1350888,376313,0.401182,2.625565
60,1014,義守大學,223,0,79523,703879,12787,3220,74822,125849,2699857,1221508,382434,43229,1.839575,1.840524
51,1005,淡江大學,517,30,71730,2585059,69948,3185,137096,284450,611503,4144086,1416802,1404,51.089744,1.824573
0,1,國立政治大學,249,34,60524,741894,24603,2978,128733,386198,2732587,2932900,1873299,235613,0.256879,0.396036

In [29]:
df.sort_values(by="全年圖書(含視聽資料及其他館藏)借閱人次(人次)", ascending=False).head()

,學校代碼,學校名稱,線上資料庫(種),光碟及其他類型資料庫(種),電子期刊(種),電子書(種),視聽資料(件),圖書閱覽座位數(個),全年圖書(含視聽資料及其他館藏)借閱人次(人次),全年圖書(含視聽資料及其他館藏)借閱冊次(冊次),全年線上及光碟資料庫(含電子書及電子期刊)檢索(人次),館藏資源,書(紙本)資源,期刊(紙本)資源,期刊數位化程度,書本數位化程度
1,2,國立清華大學,449,0,150970,3546844,122765,3440,168306,461470,239163,5545284,1350888,376313,0.401182,2.625565
64,1018,朝陽科技大學,229,12,65362,994968,50660,1290,164164,234206,1784664,1634985,523754,769,84.996099,1.899686
2,3,國立臺灣大學,598,0,54046,3206992,184316,3938,155454,481978,32772687,8525550,4196045,886763,0.060948,0.764289
51,1005,淡江大學,517,30,71730,2585059,69948,3185,137096,284450,611503,4144086,1416802,1404,51.089744,1.824573
0,1,國立政治大學,249,34,60524,741894,24603,2978,128733,386198,2732587,2932900,1873299,235613,0.256879,0.396036